export const ERAS = [
  {
    id: 1,
    start: 1950,
    end: 1957,
    label: 'PIONEER ERA',
    subtitle: '1950–1957',
    desc: 'The birth of the World Championship. Only race results and driver standings survive from this era.',
    features: ['Race Results', 'Driver Championship'],
    color: '#888888',
    tabs: ['results', 'standings'],
  },
  {
    id: 2,
    start: 1958,
    end: 1995,
    label: 'CLASSIC ERA',
    subtitle: '1958–1995',
    desc: 'Constructor championship introduced. Spans British dominance, the turbo era, and the birth of the V10.',
    features: ['Race Results', 'Driver Championship', 'Constructor Championship', 'Qualifying'],
    color: '#c8963e',
    tabs: ['results', 'standings', 'qualifying'],
  },
  {
    id: 3,
    start: 1996,
    end: 2005,
    label: 'V10 ERA',
    subtitle: '1996–2005',
    desc: 'Screaming naturally-aspirated V10s. Lap-by-lap timing data becomes available from this era onward.',
    features: ['Race Results', 'Driver & Constructor Championships', 'Qualifying', 'Lap Times'],
    color: '#e8002d',
    tabs: ['results', 'standings', 'qualifying', 'laps'],
  },
  {
    id: 4,
    start: 2006,
    end: 2011,
    label: 'V8 ERA',
    subtitle: '2006–2011',
    desc: 'Modern knockout qualifying (Q1/Q2/Q3) introduced in 2006 alongside standardised V8 engines.',
    features: ['Race Results', 'Driver & Constructor Championships', 'Q1/Q2/Q3 Qualifying', 'Lap Times'],
    color: '#ff8000',
    tabs: ['results', 'standings', 'qualifying', 'laps'],
  },
  {
    id: 5,
    start: 2012,
    end: 2020,
    label: 'HYBRID ERA',
    subtitle: '2012–2020',
    desc: 'Turbo-hybrid power units from 2014. Pit stop duration data tracked from this era onward.',
    features: ['Race Results', 'Driver & Constructor Championships', 'Qualifying', 'Lap Times', 'Pit Stops'],
    color: '#27F4D2',
    tabs: ['results', 'standings', 'qualifying', 'laps', 'pitstops'],
  },
  {
    id: 6,
    start: 2021,
    end: 2022,
    label: 'MODERN ERA',
    subtitle: '2021–2022',
    desc: 'Ground effect aerodynamics return and sprint race weekends make their debut.',
    features: ['Race Results', 'Driver & Constructor Championships', 'Qualifying', 'Lap Times', 'Pit Stops', 'Sprint Races'],
    color: '#3671C6',
    tabs: ['results', 'standings', 'qualifying', 'laps', 'pitstops', 'sprint'],
  },
];
